Wykonane zadania z zajęć nr 1 i 2
t0meck-pj/ukos2021-22_15c pull request #8
Opened 2021-10-31 17:35 UTC by s24261-pj

2021-11-02 22:16 UTC, t0meck-pj requested changes
Proszę poprawić błędy i wysłać kolejny PR

2021-11-02 22:16 UTC, t0meck-pj commented on s24261-pj-mateusz-kopczyński/zajecia1/zad11.txt
> +Używając polecenia: cd ././././././ nie przenosi mnie nigdzie, cały czas znajduję się w tym samym katalogu Obrazy
Przenosi ale cały czas do tego samego katalogu. Komputer wyliczy operację przejścia przez katalog ale docelowo wylądujesz w tym samym miejscu jednak operacja jako taka się wykona.

2021-11-02 22:16 UTC, t0meck-pj commented on s24261-pj-mateusz-kopczyński/zajecia1/zad15.txt
> +2. mkdir ukos/to/jest/dluga/nazwa
Do poprawki

2021-11-02 22:16 UTC, t0meck-pj commented on s24261-pj-mateusz-kopczyński/zajecia1/zad7.txt
> +Tutaj niestety nie wiem w jaki sposób mogę uruchomić ssh w trybie graficznym :(
Jest to nietrywialne ale się da. X11 forwarding. Niestety na szuflandii to nie działa.

2021-11-02 22:16 UTC, t0meck-pj commented on s24261-pj-mateusz-kopczyński/zajecia2/zad5.txt
> +Na bitach domyślnych praw dostępu oraz maski jest wykonywana operacja przesunięcia bitowego.
Nie. To nie jest przesunięcie bitowe.
Przesunięcie bitowe robi z np. 1 << 2 robi => 100 czyli w dziesiętnym będzie to 4 a startowaliśmy z 1
Proszę przeczytać jeszcze raz manual

2021-11-02 22:16 UTC, t0meck-pj commented on s24261-pj-mateusz-kopczyński/pamietnik.txt
> +- do czego służy narzędzie: umask i jak wykonywać przesunięcia bitowe związane z tym narzędziem
To nie przesunięcie bitowe

2021-11-02 22:16 UTC, t0meck-pj commented on s24261-pj-mateusz-kopczyński/zajecia2/zad1-2.txt
> +Zadania 1-2 wykonywaliśmy na zajęciach. Stworzyliśmy małą strukturę katalogów i przydzielaliśmy różne prawa dostępu.
Prawa czy uprawnienia?

2021-11-02 22:16 UTC, t0meck-pj commented
Proszę poprawić błędy i wysłać kolejny PR

2021-11-02 22:16 UTC, closed without merging

2021-11-03 20:43 UTC, s24261-pj commented on s24261-pj-mateusz-kopczyński/zajecia2/zad1-2.txt
> +Zadania 1-2 wykonywaliśmy na zajęciach. Stworzyliśmy małą strukturę katalogów i przydzielaliśmy różne prawa dostępu.
Prawa